import { Phraseoid } from "./phraseoid";

const names = [
  "Alice",
  "Bob",
  "Charlie",
  "David",
  "Eve",
  "Frank",
  "Grace",
  "Heidi",
  "Ivan",
  "Judy",
  "Kevin",
  "Larry",
  "Mallory",
  "Nancy",
  "Olivia",
  "Peggy",
  "Quentin",
  "Rupert",
  "Sybil",
  "Trent",
  "Ursula",
  "Victor",
  "Walter",
  "Xavier",
  "Yvonne",
  "Zelda",
];

const places = [
  "airport",
  "bank",
  "cafe",
  "diner",
  "embassy",
  "fire station",
  "gallery",
  "hospital",
  "inn",
  "jail",
  "kennel",
  "library",
  "museum",
  "newsroom",
  "office",
  "park",
  "quarry",
  "restaurant",
  "school",
  "theater",
  "university",
  "village",
  "warehouse",
  "yard",
  "zoo",
];

const colours = [
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "black",
  "white",
  "grey",
  "brown",
  "pink",
  "beige",
  "cyan",
  "magenta",
  "teal",
  "lime",
  "olive",
  "maroon",
  "navy",
  "aqua",
  "silver",
  "gold",
  "bronze",
  "platinum",
  "rose",
  "peach",
];

const animals = [
  "ant",
  "bat",
  "cat",
  "dog",
  "eel",
  "fox",
  "gnu",
  "hog",
  "imp",
  "jay",
  "kit",
  "lynx",
];

const adjectives = [
  "adorable",
  "beautiful",
  "clever",
  "daring",
  "elegant",
  "fierce",
  "graceful",
  "handsome",
  "intelligent",
  "jolly",
  "kind",
  "lovely",
  "magnificent",
  "noble",
  "optimistic",
  "proud",
  "quick",
  "resilient",
  "strong",
  "tough",
  "unique",
  "vibrant",
  "witty",
  "xenial",
  "young",
  "zany",
];

const vehicles = [
  "ambulance",
  "bus",
  "car",
  "digger",
  "elevator",
  "forklift",
  "glider",
  "helicopter",
  "icebreaker",
  "jet",
  "kayak",
  "limousine",
  "motorcycle",
  "narrowboat",
  "ocean liner",
  "plane",
  "quad bike",
  "rocket",
  "submarine",
  "tank",
  "unicycle",
  "van",
  "wagon",
  "yacht",
  "zeppelin",
];

const verbs = [
  "admire",
  "bake",
  "chase",
  "dance",
  "eat",
  "fight",
  "greet",
  "help",
  "invite",
  "jump",
  "kick",
  "laugh",
  "march",
  "navigate",
  "open",
  "paint",
  "quench",
  "read",
  "sing",
  "travel",
  "understand",
  "visit",
  "walk",
  "x-ray",
  "yodel",
  "zoom",
];

const machines = [
  "air conditioner",
  "boiler",
  "computer",
  "drill",
  "escalator",
  "fan",
  "generator",
  "heater",
  "iron",
  "juicer",
  "kettle",
  "laser",
  "microwave",
  "oven",
  "printer",
  "quern",
  "router",
  "shredder",
  "toaster",
  "umbrella",
  "vacuum cleaner",
  "washer",
  "x-ray machine",
  "yacht",
  "zipper",
];
const occupations = [
  "actor",
  "baker",
  "chef",
  "doctor",
  "engineer",
  "farmer",
  "gardener",
  "hairdresser",
  "inventor",
  "juggler",
  "knight",
  "lawyer",
  "mechanic",
  "nurse",
  "optician",
  "pilot",
  "quartermaster",
  "referee",
  "sailor",
  "teacher",
  "undertaker",
  "vet",
  "waiter",
  "{{machine}} technician",
  "{{skill}} instructor",
  "{{animal}} trainer",
  "zoologist",
];

const skills = [
  "acting",
  "baking",
  "cooking",
  "dancing",
  "engineering",
  "farming",
  "gardening",
  "hairdressing",
  "inventing",
  "juggling",
  "knighthood",
  "lawyering",
  "mechanics",
  "nursing",
  "optics",
  "piloting",
  "quartermastering",
  "refereeing",
  "sailing",
  "teaching",
  "undertaking",
  "veterinary",
  "waiting",
  "{{machine}} maintenance",
  "yoga",
  "zoology",
];

const foods = [
  "apple",
  "banana",
  "carrot",
  "date",
  "eggplant",
  "fig",
  "grape",
  "hazelnut",
  "iceberg lettuce",
  "jackfruit",
  "kiwi",
  "lemon",
  "mango",
  "nectarine",
  "olive",
  "pear",
  "quince",
  "raspberry",
  "strawberry",
  "tomato",
  "ugli fruit",
  "vanilla",
  "watermelon",
  "ximenia",
  "yam",
  "zucchini",
];

const nationalaties = [
  "Australian",
  "Belgian",
  "Canadian",
  "Danish",
  "Estonian",
  "Finnish",
  "German",
  "Hungarian",
  "Icelandic",
  "Japanese",
  "Korean",
  "Latvian",
  "Mongolian",
  "Norwegian",
  "Omani",
  "Polish",
  "Qatari",
  "Russian",
  "Swedish",
  "Tunisian",
  "Ukrainian",
  "Vietnamese",
  "Welsh",
  "Xhosa",
  "Yoruba",
  "Zulu",
];

const senses = [
  "sight",
  "hearing",
  "taste",
  "touch",
  "smell",
  "balance",
  "temperature",
  "pain",
  "time",
  "proprioception",
  "equilibrioception",
  "nociception",
  "chronoception",
  "thermoception",
  "olfaction",
  "gustation",
  "audition",
  "vision",
  "vestibular sense",
  "sense of position",
  "sense of movement",
  "sense of force",
  "sense of effort",
  "sense of heaviness",
  "sense of resistance",
];

const softwareActivities = [
  "making",
  "building",
  "developing",
  "creating",
  "designing",
  "crafting",
  "producing",
  "fabricating",
  "manufacturing",
  "engineering",
  "writing",
  "programming",
  "coding",
  "hacking together",
];

const genres = [
  "action",
  "adventure",
  "arcade",
  "board",
  "card",
  "casual",
  "educational",
  "fighting",
  "music",
  "platform",
  "puzzle",
  "racing",
  "role-playing",
  "shooter",
  "simulation",
  "sports",
  "strategy",
  "survival",
  "trivia",
  "word",
];

const minorBritishCelebrities = [
  "Ainsley Harriott",
  "Barbara Windsor",
  "Christopher Biggins",
  "Dame Edna Everage",
  "Eamonn Holmes",
  "Fern Britton",
  "Gok Wan",
  "Holly Willoughby",
  "Ian Beale",
  "Jedward",
  "Keith Lemon",
  "Lorraine Kelly",
  "Michael Barrymore",
  "Nigel Farage",
  "Olly Murs",
  "Piers Morgan",
  "Queen Elizabeth II",
  "Rylan Clark-Neal",
  "Sue Barker",
  "Tess Daly",
  "Ulrika Jonsson",
  "Vernon Kay",
  "Wendy Richard",
  "Xander Armstrong",
  "Yvette Fielding",
  "Zoe Ball",
  "Alan Titchmarsh",
  "Basil Brush",
  "Cilla Black",
  "Dale Winton",
  "Eddie the Eagle",
  "Fiona Bruce",
  "Gordon Ramsay",
  "Hilda Ogden",
  "Ivor the Engine",
  "Jools Holland",
  "Katie Price",
  "Les Dennis",
  "Mick Hucknall",
  "Noddy Holder",
  "Ozzy Osbourne",
  "Pamela Anderson",
  "Quincy Jones",
  "Ringo Starr",
  "Shakin' Stevens",
  "Tina Turner",
  "Uri Geller",
  "Vic Reeves",
  "Wincey Willis",
  "Xavier Roberts",
  "Yvette Cooper",
  "Zippy and George",
];

const videoGameStudios = [
  "Activision",
  "Blizzard",
  "Capcom",
  "DICE",
  "EA",
  "FromSoftware",
  "Guerilla Games",
  "Hello Games",
  "Infinity Ward",
  "Jagex",
  "Konami",
  "LucasArts",
  "Mojang",
  "Nintendo",
  "Obsidian",
  "Pandemic",
  "Quantic Dream",
  "Rare",
  "Sega",
  "Traveller's Tales",
  "Ubisoft",
  "Valve",
  "Warner Bros.",
  "Xbox Game Studios",
  "Yager Development",
  "Zynga",
];

const objectiveModifiers = [
  "quickly",
  "carefully",
  "quietly",
  "sneakily",
  "safely",
  "efficiently",
  "effectively",
  "bravely",
  "boldly",
  "cautiously",
  "lazily",
];

const objectives = [
  "get to",
  "have to",
  "try to",
  "try really hard to",
  "try not to",
];

const actions = [
  "find",
  "collect",
  "destroy",
  "avoid",
  "defend",
  "attack",
  "rescue",
  "save",
  "steal",
  "escape",
];

const sillyActions = [
  "hug",
  "kiss",
  "cuddle",
  "snuggle",
  "tickle",
  "tuck in",
  "tuck into",
  "pet",
  "stroke",
  "feed",
  "water",
  "bathe",
  "groom",
];

const collectibles = [
  "coin",
  "key",
  "power-up",
  "weapon",
  "item",
  "treasure",
  "gem",
  "crystal",
  "artifact",
  "relic",
  "jewel",
];

const sillyCollectibles = [
  "butterfly",
  "bubble",
  "flower",
  "heart",
  "star",
  "smile",
  "hug",
  "kiss",
  "rainbow",
  "unicorn",
  "sunshine",
  "puppy",
  "kitten",
  "candy",
  "cookie",
  "cupcake",
  "donut",
  "ice cream",
  "lollipop",
  "marshmallow",
  "chocolate",
  "pizza",
  "burger",
  "fries",
  "soda",
  "milkshake",
  "egg",
  "bacon",
  "Easter egg",
];

const surrealCollectibles = [
  "dream",
  "nightmare",
  "memory",
  "thought",
  "idea",
  "feeling",
  "emotion",
  "sensation",
  "perception",
  "illusion",
  "hallucination",
  "delusion",
  "fantasy",
  "vision",
  "revery",
  "daydream",
  "night terror",
  "phantasm",
  "apparition",
  "spectre",
  "phantom",
  "wraith",
  "shadow",
  "echo",
  "whisper",
  "murmur",
  "rumour",
  "gossip",
  "secret",
];

const terms = {
  minorBritishCelebrity: minorBritishCelebrities,
  genre: genres,
  name: names,
  place: places,
  colour: colours,
  animal: animals,
  adjective: adjectives,
  vehicle: vehicles,
  verb: verbs,
  colouredThing: ["{{colour}} {{thing}}"],
  thing: [
    "{{colour}} {{animal}}",
    "{{adjective}} {{animal}}",
    "{{colour}} {{vehicle}}",
  ],
  size: ["small", "medium", "large"],
  sizedThing: ["{{size}} {{thing}}"],
  occupation: occupations,
  skill: skills,
  machine: machines,
  foods: foods,
  nationality: nationalaties,
  softwareActivity: softwareActivities,
  videoGameStudio: videoGameStudios,
  partner: [
    "neighbour",
    "friend",
    "colleague",
    "boss",
    "partner",
    "estate",
    "best friend",
    "team",
    "mate",
    "old boss",
    "new boss",
    "ex-partner",
    "{{animal}} walker",
  ],
  who: [
    "we're",
    "I'm",
    "they're",
    "{{minorBritishCelebrity}} is",
    "{{minorBritishCelebrity}}'s {{partner}} is",
    "{{videoGameStudio}} is",
    "{{videoGameStudio}}'s {{top developer is|optional}}",
  ],
  objectiveModifier: objectiveModifiers,
  objective: objectives,
  action: [...actions, ...sillyActions],
  collectible: [...collectibles, ...sillyCollectibles, ...surrealCollectibles],
};

const phrases = [
  "{{who|capitalize}} {{softwareActivity}} {{genre|indefinite}} game where you {{objectiveModifier|optional}} {{objective}} {{action}} {{collectible|plural}}.",
];

const phraseoid = new Phraseoid();
phraseoid.terms = terms;
phraseoid.phrases = phrases;
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
console.log(phraseoid.generatePhrase());
